# Generated by Django 4.2.9 on 2024-01-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='persona',
            field=models.CharField(choices=[('manager', 'Manager'), ('sales', 'Sales/Account Owner')], max_length=10),
        ),
    ]
